# Generated by Django 3.1.4 on 2021-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtues', '0002_auto_20201228_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='amount',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
