# Generated by Django 3.1.4 on 2021-03-04 06:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtues', '0003_auto_20210228_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('condition', models.CharField(choices=[('Highest', 'Highest'), ('Minimum', 'Minimum')], max_length=10)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('tasks', models.ManyToManyField(to='virtues.DailyTask')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
