# Generated by Django 3.1.4 on 2021-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtues', '0004_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
